Repository HICURE/HICURE, pull requests merged in 2024-07, with the labels that each got.

#4 테스트
  test.txt
  test.txt.txt
Labels: 🐈‍⬛7lyeon🐈‍⬛

#5 [FEATURE] 시작화면 Activity 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/AppStart.kt
  app/src/main/res/layout/activity_app_start.xml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧

#6 Serve Info activity 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/ServeInfo.kt
  app/src/main/res/layout/activity_serve_info.xml
Labels: 🐈‍⬛7lyeon🐈‍⬛, 🫧FEATURE🫧

#17 add info box
  app/src/main/java/com/example/hicure/ServeInfo.kt
  app/src/main/res/drawable/infobox.xml
  app/src/main/res/layout/activity_serve_info.xml
Labels: 🐈‍⬛7lyeon🐈‍⬛, 🎨DESIGN🎨

#23 [FEATURE] Nayeong/20-feature-titlebar
  .github/ISSUE_TEMPLATE/tip_request.yml
  .github/pull_request_template.md
  app/src/main/java/com/example/hicure/AppStart.kt
  app/src/main/java/com/example/hicure/MainActivity.kt
  app/src/main/res/drawable/behind_action_title.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/background_circle.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧, 🎨DESIGN🎨

#30 [FEATURE] Nayeong/25 feature check
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/AppStart.kt
  app/src/main/java/com/example/hicure/CheckId.kt
  app/src/main/res/drawable/back_wave_high.xml
  app/src/main/res/drawable/edit_text_frame.xml
  app/src/main/res/drawable/pop_up_frame.xml
  app/src/main/res/drawable/x.xml
  app/src/main/res/font/roboto_bold.xml
  app/src/main/res/layout/activity_check_id.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🦖gjsk132🦖, 🎨DESIGN🎨, ⏳PROGRESS⏳
