Repository HICURE/HICURE, pull requests merged in 2024-08, with the labels that each got.

#40 [FEATURE] Nayeong/25 feature check
  app/build.gradle.kts
  app/google-services.json
  app/src/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/AppStart.kt
  app/src/main/java/com/example/hicure/CheckId.kt
  app/src/main/java/com/example/hicure/InitialSurvey.kt
  app/src/main/java/com/example/hicure/MainActivity.kt
  app/src/main/java/com/example/hicure/User.kt
  app/src/main/java/com/example/hicure/UserInfo.kt
  app/src/main/res/drawable/blue_frame.xml
  app/src/main/res/drawable/check.xml
  app/src/main/res/drawable/gray_frame.xml
  app/src/main/res/drawable/inquiry_button.xml
  app/src/main/res/drawable/lock.xml
  app/src/main/res/drawable/user_back.xml
  app/src/main/res/drawable/user_icon.xml
  app/src/main/res/drawable/user_info.xml
  app/src/main/res/drawable/yellow_frame.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_user_info.xml
  app/src/main/res/layout/check_id.xml
  app/src/main/res/layout/inquiry.xml
  app/src/main/res/layout/my_info.xml
  app/src/main/res/layout/user_survey.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧

#45 [FEATURE] Nayeong/44 feature ble connect test
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/BlankFragment.kt
  app/src/main/java/com/example/hicure/BleAdapter.kt
  app/src/main/java/com/example/hicure/BleConnect.kt
  app/src/main/java/com/example/hicure/BluetoothUtils.kt
  app/src/main/java/com/example/hicure/Constants.kt
  app/src/main/java/com/example/hicure/DiveiceAdapter.kt
  app/src/main/java/com/example/hicure/MainActivity.kt
  app/src/main/java/com/example/hicure/NewMeasume.kt
  app/src/main/java/com/example/hicure/UserInfo.kt
  app/src/main/java/com/example/hicure/bleAdapter.kt
  app/src/main/res/layout/activity_ble_connect.xml
  app/src/main/res/layout/activity_new_measume.xml
  app/src/main/res/layout/check_connect.xml
  app/src/main/res/layout/device_info.xml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧, ⏳PROGRESS⏳, merge하고 싶어요

#48 [FEATURE] Nayeong/32 feature user info 2
  app/src/main/java/com/example/hicure/CustomAdapter.kt
  app/src/main/java/com/example/hicure/InitialSurvey.kt
  app/src/main/java/com/example/hicure/Survey.kt
  app/src/main/java/com/example/hicure/UserInfo.kt
  app/src/main/res/layout/activity_survey.xml
  app/src/main/res/layout/activity_user_info.xml
  app/src/main/res/layout/user_survey.xml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧, merge하고 싶어요

#50 [FEATURE] Nayeong/12 feature start
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/AppStart.kt
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧, merge하고 싶어요

#56 [FEATURE] Nayeong/44 feature ble connect test
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/AppStart.kt
  app/src/main/java/com/example/hicure/BleConnect.kt
  app/src/main/java/com/example/hicure/NewMeasume.kt
  app/src/main/res/drawable/battery_bar.xml
  app/src/main/res/drawable/measure_background.xml
  app/src/main/res/drawable/progress_bar.xml
  app/src/main/res/drawable/wind.xml
  app/src/main/res/layout/activity_new_measume.xml
  app/src/main/res/layout/background_circle.xml
  app/src/main/res/layout/check_result.xml
  app/src/main/res/values/colors.xml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧, 🎨DESIGN🎨, merge하고 싶어요

#59 [FEATURE] Suhyun/alarm db
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/AlarmList.kt
  app/src/main/java/com/example/hicure/MainActivity.kt
  app/src/main/java/com/example/hicure/ServeInfo.kt
  app/src/main/java/com/example/hicure/UserInfo.kt
  app/src/main/java/com/example/hicure/alarm/AlarmDao.kt
  app/src/main/java/com/example/hicure/alarm/AlarmDatabase.kt
  app/src/main/java/com/example/hicure/alarm/AlarmEntity.kt
  app/src/main/java/com/example/hicure/alarm/AlarmList.kt
  app/src/main/java/com/example/hicure/alarm/AlarmReceiver.kt
  app/src/main/java/com/example/hicure/alarm/AlarmRepository.kt
  app/src/main/java/com/example/hicure/alarm/CustomTimePicker.kt
  app/src/main/java/com/example/hicure/alarm/NotificationHelper.kt
  app/src/main/java/com/example/hicure/alarm/SetAlarm.kt
  app/src/main/res/drawable/set_alarm_box_blue.xml
  app/src/main/res/drawable/set_alarm_box_pink.xml
  app/src/main/res/drawable/set_alarm_box_yellow.xml
  app/src/main/res/drawable/set_alarm_cancel_button_box.xml
  app/src/main/res/drawable/set_alarm_name_text_field.xml
  app/src/main/res/drawable/set_alarm_save_button_box_blue.xml
  app/src/main/res/drawable/set_alarm_save_button_box_pink.xml
  app/src/main/res/drawable/set_alarm_save_button_box_yellow.xml
  app/src/main/res/layout/activity_alarm_list.xml
  app/src/main/res/layout/activity_set_alarm.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: 🐧suhyun113🐧, 🫧FEATURE🫧, merge하고 싶어요

#58 [FEATURE] Nayeong/57 feature serveinfo
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/MainActivity.kt
  app/src/main/java/com/example/hicure/ServeInfo.kt
  app/src/main/java/com/example/hicure/UserInfo.kt
  app/src/main/java/com/example/hicure/serveinfo/ActivityAnatomy.kt
  app/src/main/java/com/example/hicure/serveinfo/ActivityBreathExercises.kt
  app/src/main/java/com/example/hicure/serveinfo/ActivityDeviceScience.kt
  app/src/main/java/com/example/hicure/serveinfo/ActivityHealthyFoods.kt
  app/src/main/java/com/example/hicure/serveinfo/ActivityImportanceOfLungCapacity.kt
  app/src/main/java/com/example/hicure/serveinfo/ActivityLungCapacityPrediction.kt
  app/src/main/java/com/example/hicure/serveinfo/ActivityMeasurementPrinciple.kt
  app/src/main/java/com/example/hicure/serveinfo/FullScreenImageActivity.kt
  app/src/main/java/com/example/hicure/serveinfo/InfoAdapter.kt
  app/src/main/java/com/example/hicure/serveinfo/InfoItem.kt
  app/src/main/java/com/example/hicure/serveinfo/ServeInfo.kt
  app/src/main/res/drawable/image1.png
  app/src/main/res/drawable/image2.png
  app/src/main/res/drawable/info_frame.xml
  app/src/main/res/layout/activity_full_screen_image.xml
  app/src/main/res/layout/activity_serve_info.xml
  app/src/main/res/layout/card_info.xml
  app/src/main/res/layout/info_details.xml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧, 🎨DESIGN🎨, ⏳PROGRESS⏳

#60 Suhyun/35 feature setalarm
  app/src/main/java/com/example/hicure/alarm/AlarmList.kt
  app/src/main/res/layout/activity_alarm_list.xml
  app/src/main/res/values/strings.xml
Labels: 🐧suhyun113🐧, 🫧FEATURE🫧, merge하고 싶어요

#62 [FEATURE] Nayeong/57 feature serveinfo
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/AppStart.kt
  app/src/main/java/com/example/hicure/Calendar.kt
  app/src/main/java/com/example/hicure/FirebaseCheckDate.kt
  app/src/main/java/com/example/hicure/MainActivity.kt
  app/src/main/java/com/example/hicure/User.kt
  app/src/main/java/com/example/hicure/serveinfo/InfoItem.kt
  app/src/main/java/com/example/hicure/serveinfo/ServeInfo.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧, 🎨DESIGN🎨, merge하고 싶어요

#66 [FEATURE] Nayeong/64 feature measume data
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/AppStart.kt
  app/src/main/java/com/example/hicure/BleAdapter.kt
  app/src/main/java/com/example/hicure/Calendar.kt
  app/src/main/java/com/example/hicure/FirebaseCheckDate.kt
  app/src/main/java/com/example/hicure/InitialSurvey.kt
  app/src/main/java/com/example/hicure/MainActivity.kt
  app/src/main/java/com/example/hicure/NewMeasume.kt
  app/src/main/java/com/example/hicure/Survey.kt
  app/src/main/java/com/example/hicure/User.kt
  app/src/main/java/com/example/hicure/UserInfo.kt
  app/src/main/java/com/example/hicure/serveinfo/ActivityLungCapacityPrediction.kt
  app/src/main/java/com/example/hicure/serveinfo/InfoAdapter.kt
  app/src/main/java/com/example/hicure/serveinfo/ServeInfo.kt
  app/src/main/res/drawable/setting.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_survey.xml
  app/src/main/res/layout/activity_user_info.xml
  app/src/main/res/layout/card_info.xml
  app/src/main/res/layout/inquiry.xml
  app/src/main/res/layout/my_info.xml
  app/src/main/res/layout/survey_question.xml
  app/src/main/res/layout/user_survey.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧, 🎨DESIGN🎨, ⚒️FIX⚒️, merge하고 싶어요

#71 [FEATURE] Nayeong/64 feature measume data
  app/src/main/java/com/example/hicure/Calendar.kt
  app/src/main/java/com/example/hicure/MainActivity.kt
  app/src/main/java/com/example/hicure/Survey.kt
  app/src/main/java/com/example/hicure/linechart.kt
  app/src/main/res/layout/activity_survey.xml
Labels: 🦖gjsk132🦖, ⚒️FIX⚒️, merge하고 싶어요

#72 merge develop into main
  app/src/main/java/com/example/hicure/Calendar.kt
  app/src/main/java/com/example/hicure/MainActivity.kt
  app/src/main/java/com/example/hicure/Survey.kt
  app/src/main/java/com/example/hicure/alarm/AlarmList.kt
  app/src/main/java/com/example/hicure/linechart.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_survey.xml
Labels: ⭐MERGE⭐

#74 [FEATURE] Suhyun/61 feature pushalarm
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hicure/alarm/AlarmList.kt
  app/src/main/java/com/example/hicure/alarm/AlarmReceiver.kt
  app/src/main/java/com/example/hicure/alarm/AlarmRepository.kt
  app/src/main/java/com/example/hicure/alarm/AlertReceiver.kt
  app/src/main/java/com/example/hicure/alarm/CustomTimePicker.kt
  app/src/main/java/com/example/hicure/alarm/NotificationHelper.kt
  app/src/main/java/com/example/hicure/alarm/SetAlarm.kt
  app/src/main/res/drawable/ic_alarm_bell.xml
  app/src/main/res/drawable/set_alarm_box_blue.xml
  app/src/main/res/drawable/set_alarm_box_pink.xml
  app/src/main/res/drawable/set_alarm_box_yellow.xml
  app/src/main/res/layout/activity_alarm_list.xml
  app/src/main/res/layout/activity_set_alarm.xml
  app/src/main/res/values/strings.xml
Labels: 🐧suhyun113🐧, 🫧FEATURE🫧, merge하고 싶어요

#78 [FEATURE] Nayeong/64 feature measume data
  app/src/main/java/com/example/hicure/alarm/NotificationHelper.kt
  app/src/main/res/drawable/app_icon.xml
Labels: 🦖gjsk132🦖, 🫧FEATURE🫧, 🎨DESIGN🎨, ⭐MERGE⭐
